Create navigation bar & Fragments
shashank205/MyInstagram pull request #1
Opened 2019-02-06 08:17 UTC by shashank205

Modified navigation bar and created fragments

2019-02-06 08:47 UTC, ghost requested changes
Please update the codes as per the comments.

2019-02-06 08:47 UTC, MohammedAtif commented on app/build.gradle
> +        minSdkVersion 26
why did you change min version to 26?

2019-02-06 08:47 UTC, MohammedAtif commented on app/src/main/java/com/example/myinstagram/FragmentFactory.java
> +    public static Fragment getFragment(FragmentType fragmentType) {
Factory methods must be in individual fragments

2019-02-06 08:47 UTC, MohammedAtif commented on app/src/main/java/com/example/myinstagram/MainActivity.java
> +    public void replaceFragment(FragmentType fragmentType) {
you have to define an interface to manage fragment transactions

2019-02-06 08:47 UTC, MohammedAtif commented on app/src/main/java/com/example/myinstagram/fragment/FragmentType.java
> +package com.example.myinstagram.fragment;
Try to use integer constants instead of enums wherever possible.
Refer - https://developer.android.com/topic/performance/memory

2019-02-06 08:47 UTC, MohammedAtif commented on app/src/main/java/com/example/myinstagram/fragment/HomeFragment.java
> +
newInstance method must be added here

2019-02-06 08:47 UTC, MohammedAtif commented on app/src/main/res/layout/fragment_home.xml
> +<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
Replace FrameLayout with ConstraintLayout going forward

2019-02-06 08:53 UTC, shashank205 commented on app/build.gradle
> +        minSdkVersion 26
Got this error for OkHttp dependency
Error: Invoke-customs are only supported starting with Android O (--min-api 26)

2019-02-06 08:54 UTC, MohammedAtif commented on app/build.gradle
> +        minSdkVersion 26
Try to look for a solution that supports minimum API of at least 23

2019-02-06 10:15 UTC, ghost requested changes

2019-02-06 10:15 UTC, MohammedAtif commented on app/src/main/java/com/example/myinstagram/fragment/HomeFragment.java
> +    public static HomeFragment newInstance() {
you have to use this method directly instead of using a helper class. (FragmentFactory)

2019-02-07 13:07 UTC, ghost approved these changes

2019-02-07 13:07 UTC, merged