Dev1
shashank205/MyInstagram pull request #2
Opened 2019-02-11 07:25 UTC by shashank205

Refactor code & load image using url

2019-02-11 07:41 UTC, ghost requested changes

2019-02-11 07:41 UTC, MohammedAtif commented on .idea/sonarlint/issuestore/8/e/8e5443d8d30a7de357d523dd957ecd23f8d46697
> +
Can you add .idea folder to gitignore and update the build caches?

2019-02-11 07:41 UTC, MohammedAtif commented on app/src/main/java/com/example/myinstagram/fragment/HomeFragment.java
> +        super.onViewCreated(view, savedInstanceState);
RecyclerView setup must be done in OnViewCreated because it is part of post view creation but not handled by binding

2019-02-11 08:04 UTC, shashank205 commented on app/src/main/java/com/example/myinstagram/fragment/HomeFragment.java
> +        super.onViewCreated(view, savedInstanceState);
RecyclerView setup is in OnViewCreated only

2019-02-11 09:46 UTC, MohammedAtif commented on .gitignore
> +/.idea
it should be ".idea/" forward slash in the end means given item is a folder, otherwise .gitignore considers it as a file.

2019-02-26 06:04 UTC, ghost approved these changes

2019-02-26 06:04 UTC, ghost commented on app/src/main/java/com/example/myinstagram/adapters/PostsAdapter.java
> +    class PostViewHolder extends RecyclerView.ViewHolder {
Can you update this adapter with databinding?

2019-02-26 06:04 UTC, ghost commented on app/src/main/java/com/example/myinstagram/dependency_injection/MainActivityBuilder.java
> +interface MainActivityBuilder {
Never make modules specific to an activity, modules must be specific to task,
For example, FragmentInjectionModule, ResourceInjectIonModule (Shared Preference, Okhttp, etc)

2019-02-26 06:04 UTC, ghost commented on app/src/main/java/com/example/myinstagram/fragments/HomeFragment.java
> +        AndroidSupportInjection.inject(this);
Inject must happen in onCreate, until and unless you are using injected variables before onCreate

2019-02-26 06:04 UTC, ghost commented on app/src/main/java/com/example/myinstagram/fragments/HomeFragment.java
> +public class HomeFragment extends Fragment implements HttpCallBack {
Create anonymous objects where ever possible instead of implementing the interface and exposing the methods. This alters the purpose of class and interface implementations.

2019-02-26 06:04 UTC, ghost commented on app/src/main/java/com/example/myinstagram/fragments/HomeFragment.java
> +    private void fetchPostsFromServer() {
All kind of data manipulations and handling must happen in ViewModel. As discussed, fragments responsibility is just to provide view to show that data.

2019-02-26 06:04 UTC, merged